### ISSUE TITLE
Replace deprecated dependency "gutil"

### ISSUE THREAD

**Issue by shockthetoast** [Perkovec/gulp-sass-unicode#4]
Gulp deprecated gutil and wants all plugins to replace it with something else.
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

It looks like the only parts of gutil being used are PluginError and File:

gutil.PluginError => https://www.npmjs.com/package/plugin-error
gutil.File => https://www.npmjs.com/package/vinyl

Thank you!

**Comment by Perkovec** [comment]
Fixed in https://github.com/Perkovec/gulp-sass-unicode/commit/c6952c99f08d691cc772e68bfb18034e6e278b57

**Comment by shockthetoast** [comment]
Thanks! That was incredibly fast!
