### ISSUE TITLE
The regular expression match for multiple characters is greedy, grabs too much of a minified file.

### ISSUE THREAD

**Issue by shockthetoast** [Perkovec/gulp-sass-unicode#5]
If we use the "compressed" output mode in SASS, and there are any matching quotes later in the file, gulp-sass-unicode will match from the opening quote of content to the last quote it finds.

Here's a simple example. We start with this SCSS:
```
.sample-class::after {
    content: "";
}

.sample-class2 {
    font-family: "Roboto";
}
```

This is compressed to:
`.sample-class::after{content:""}.sample-class2{font-family:"Roboto"}`

gulp-sass-unicode then outputs this:
` .sample-class::after{content: "\22\7d\2e\73\61\6d\70\6c\65\2d\63\6c\61\73\73\32\7b\66\6f\6e\74\2d\66\61\6d\69\6c\79\3a\22\52\6f\62\6f\74\6f"}`

I believe updating the regex to be non-greedy should be enough to fix this.

**Comment by shockthetoast** [comment]
I believe this regular expression will work:
`/content: *"([^"]*)"/g;`

I was having trouble getting the test to run locally so I couldn't confirm it, and didn't want to do a pull request if I couldn't test it on my end.

**Comment by Perkovec** [comment]
@shockthetoast I've update dependencies in project and now you can run tests locally

**Comment by shockthetoast** [comment]
@Perkovec The test issue I had was with my git settings. My local files had been changed to windows line endings, which caused the font-awesome.css file (with CRLF) not to match the output from SASS (which was LF).

I've fixed that and submitted a pull request (#6).

**Comment by Perkovec** [comment]
Fixed by https://github.com/Perkovec/gulp-sass-unicode/pull/6

**Comment by shockthetoast** [comment]
Thank you!
