### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by FredericSavard** [Perkovec/gulp-sass-unicode#7]
Your last change caused several problems for us.

e.g.
**content: "\2022";** is now transformed into **content:"\5c\32\30\32\32";**
**"\f26e"** is now transformed into **"\5c\66\32\36\65"**
**"myString"** is now transformed into **"\6d\79\53\74\72\69\6e\67"**

We had to get back to 1.0.1 version.

**Comment by Perkovec** [comment]
@shockthetoast

**Comment by shockthetoast** [comment]
@FredericSavard That's strange. It looks as though it is somehow getting processed twice. `\5c` is the code for `\`, `\32` is the code for `2`, etc. So running `\2022` through would produce `\5c\32\30\32\32`.

I have seen some instances where SCSS would convert escape sequences to unicode, and leave some as escape sequences. For example:
https://github.com/sass/sass/issues/1395#issuecomment-397805258

I can see this likely being the case, with gulp-sass-unicode not being able to tell where there are codes that need to be converted and where there are not.

If you skip running through gulp-sass-unicode, does the resulting CSS have a mix of escape sequences and unicode characters? If so, could you provide snippet of the SCSS that result in each?

**Comment by shockthetoast** [comment]
Actually, it looks like it's as simple as variables vs. directly entering content.

For example, this scss...
```
$fa-var-angle-left: "\f104";

.selector-var {
    &::before {
        content: $fa-var-angle-left;
    }
}

.selector-direct {
    &::before {
        content: "\f104";
    }
}
```

...results in this...
```
@charset "UTF-8";
.selector-var::before {
  content: ""; }

.selector-direct::before {
  content: "\f104"; }
```
So the trick is to tell which characters need to be converted to an escape sequence, and which already are.

**Comment by shockthetoast** [comment]
@Perkovec I have a fix, but it requires specifying a range of which codepoints get converted and which get left alone. My suggestion would be to convert any codepoint above 127, which is the max for standard ASCII. This prevents converting standard strings like the example `"myString"`, as well as skipping any escape sequences.

If that sounds like a reasonable plan I can do a pull request.

**Comment by Perkovec** [comment]
Fixed with https://github.com/Perkovec/gulp-sass-unicode/pull/8

**Comment by FredericSavard** [comment]
Works fine, thanks
